version: "3.9"

services:
  db:
    image: postgres:15
    container_name: investcontrol_db
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB:
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    container_name: investcontrol_backend
    build:
      context: ..
      dockerfile: infra/docker/backend.Dockerfile
    environment:
      DATABASE_URL:
      UVICORN_RELOAD: "false"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"


  frontend:
    container_name: investcontrol_frontend
    build:
      context: ..
      dockerfile: infra/docker/frontend.Dockerfile
    environment:
      VITE_API_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "5173:5173"

  
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: investcontrol_prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend

  
  grafana:
    image: grafana/grafana:10.4.4
    container_name: investcontrol_grafana
    environment:
      GF_SECURITY_ADMIN_USER:
      GF_SECURITY_ADMIN_PASSWORD: 
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus


volumes:
  db_data:
  prometheus_data:
  grafana_data:
